apiVersion: v2
name: bitcoin
version: 0.0.0
dependencies:
  - name: app-template
    alias: bitcoind
    version: 3.2.1
    repository: https://bjw-s.github.io/helm-charts
  - name: app-template
    alias: lnd
    version: 3.2.1
    repository: https://bjw-s.github.io/helm-charts
  - name: app-template
    alias: tor
    version: 3.2.1
    repository: https://bjw-s.github.io/helm-charts
  - name: app-template
    alias: thunderhub
    version: 3.2.1
    repository: https://bjw-s.github.io/helm-charts
#  - name: app-template
#    alias: rtl
#    version: 2.6.0
#    repository: https://bjw-s.github.io/helm-charts
