bitcoind:
  global:
    nameOverride: bitcoind

  controllers:
    main:
      containers:
        main:
          image:
            repository: lncm/bitcoind
            tag: v26.0
#          resources:
#            limits:
#              cpu: 400m
#              memory: 1Gi
          probes:
            liveness: &probes
              spec:
                initialDelaySeconds: 120
            readiness: *probes
            startup: *probes
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

  persistence:
    config:
      enabled: true
      type: secret
      name: bitcoind-secrets
      globalMounts:
        - path: /data/.bitcoin/bitcoin.conf
          subPath: bitcoin.conf
    bitcoin:
      enabled: true
      existingClaim: bitcoind-data
      globalMounts:
        - path: /data/.bitcoin

  service:
    main:
      ports:
        http:
          enabled: false
        rpc:
          enabled: true
          port: 8333
        p2p:
          enabled: true
          port: 8332
        zmqblk:
          enabled: true
          port: 28332
        zmqtx:
          enabled: true
          port: 28333

tor:
  global:
    nameOverride: tor

  controllers:
    main:
      containers:
        main:
          image:
            repository: lncm/tor
            tag: 0.4.7.13
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

  persistence:
    torrc:
      enabled: true
      type: secret
      name: tor-secrets
      globalMounts:
        - path: /etc/tor/torrc
          subPath: torrc

  service:
    main:
      ports:
        http:
          enabled: false
        socks:
          enabled: true
          port: 9050
          protocol: TCP
        control:
          enabled: true
          port: 9051
          protocol: TCP

lnd:
  global:
    nameOverride: lnd

  controllers:
    main:
      initContainers:
        01-init-db:
          image:
            repository: ghcr.io/onedr0p/postgres-init
            tag: 15.5
            pullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: lnd-secrets
      containers:
        main:
          image:
            repository: lightninglabs/lnd
            tag: v0.17.3-beta
          env:
            HOME: "/data"
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

  persistence:
    config:
      enabled: true
      type: secret
      name: lnd-secrets
      globalMounts:
        - path: /data/.lnd/lnd.conf
          subPath: lnd.conf
        - path: /data/.lnd/password.txt
          subPath: password.txt
    data:
      enabled: true
      existingClaim: lnd-data
      globalMounts:
        - path: /data/.lnd

  service:
    main:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: default
      ports:
        http:
          enabled: false
        p2p:
          enabled: true
          port: 9735
          protocol: TCP
        grpc:
          enabled: true
          port: 10009
          protocol: TCP
        rest:
          enabled: true
          port: 8080

thunderhub:
  global:
    nameOverride: thunderhub

  controllers:
    main:
      containers:
        main:
          image:
            repository: apotdevin/thunderhub
            tag: v0.13.30
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

  persistence:
    config:
      enabled: true
      type: secret
      name: thunderhub-secrets
      globalMounts:
        - path: /app/.env.local
          subPath: env
        - path: /app/thubConfig.yaml
          subPath: thubConfig.yaml
    lnd:
      enabled: true
      existingClaim: lnd-data
      globalMounts:
        - path: /data/.lnd

  service:
    main:
      ports:
        http:
          port: 3000

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "thunderhub.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: thunderhub-tls-certificate
          hosts:
            - *host

#rtl:
#  global:
#    nameOverride: rtl
#
#  controllers:
#    main:
#      containers:
#        main:
#          image:
#            repository: shahanafarooqui/rtl
#            tag: 0.12.0
#      pod:
#        securityContext:
#          runAsUser: 1000
#          runAsGroup: 1000
#          fsGroup: 1000
#          fsGroupChangePolicy: OnRootMismatch
#
#  service:
#    main:
#      ports:
#        http:
#          port: 3000
