bitcoind:
  global:
    nameOverride: bitcoind

  controllers:
    main:
      containers:
        main:
          image:
            repository: lncm/bitcoind
            tag: v26.0
          resources:
            limits:
              cpu: 1200m
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

  persistence:
    bitcoin:
      enabled: true
      type: hostPath
      hostPath: /home/ant0n/bitcoin
      accessMode: ReadWriteOnce
      size: 1Ti
      globalMounts:
        - path: /data/.bitcoin
      annotations:
        'k8up.io/backup': 'false'

  service:
    main:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: default
      ports:
        http:
          enabled: false
        rpc:
          enabled: true
          port: 8333
        p2p:
          enabled: true
          port: 8332
        zmqblk:
          enabled: true
          port: 28332
        zmqtx:
          enabled: true
          port: 28333

tor:
  global:
    nameOverride: tor

  controllers:
    main:
      containers:
        main:
          image:
            repository: lncm/tor
            tag: 0.4.7.13
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

  persistence:
    script:
      enabled: true
      type: secret
      name: tor-secrets
      globalMounts:
        - path: /etc/tor/torrc
          subPath: torrc

  service:
    main:
      ports:
        http:
          enabled: false
        socks:
          enabled: true
          port: 9050
        control:
          enabled: true
          port: 9051
