kube-prometheus-stack:
  grafana:
    enabled: false
    forceDeployDatasources: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false

prometheus-pushgateway:
  serviceMonitor:
    enabled: true
    namespace: monitoring-system

influxdb:
  persistence:
    storageClass: truenas-iscsi
    size: 2Gi
  service:
    type: LoadBalancer
  config:
    graphite:
      enabled: true
      database: graphite
      bind-address: ":2003"
      protocol: tcp
      consistency-lvel: one
      templates:
        - "*.app env.service.resource.measurement"
        - "servers.* .host.resource.measurement.field*"