apiVersion: v1
kind: ConfigMap
metadata:
  name: influx-datasource
  labels:
    grafana_datasource: "1"
data:
  influxdatasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        database: graphite
        url: http://monitoring-system-influxdb.monitoring-system.svc.cluster.local:8086