apiVersion: v2
name: jellyfin
version: 0.0.0
dependencies:
  - name: app-template
    alias: jellyfin
    version: 1.5.1
    repository: https://bjw-s.github.io/helm-charts
  - name: app-template
    alias: jellyseerr
    version: 1.5.1
    repository: https://bjw-s.github.io/helm-charts