jellyfin:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "ipv4.cloudton.de"
        hajimari.io/appName: Jellyfin
        hajimari.io/icon: filmstrip
      hosts:
        - host: &host jellyfin.cloudton.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *host
