app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/dgtlmoon/changedetection.io
            tag: 0.45.9
          env:
            USE_X_SETTINGS: 1
            PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123
        browser:
          image:
            repository: docker.io/browserless/chrome
            tag: latest
            pullPolicy: IfNotPresent
          env:
            - { name: SCREEN_WIDTH, value: "1920" }
            - { name: SCREEN_HEIGHT, value: "1024" }
            - { name: SCREEN_DEPTH, value: "16" }
            - { name: ENABLE_DEBUGGER, value: "false" }
            - { name: PREBOOT_CHROME, value: "true" }
            - { name: CONNECTION_TIMEOUT, value: "300000" }
            - { name: MAX_CONCURRENT_SESSIONS, value: "10" }
            - { name: CHROME_REFRESH_TIME, value: "600000" }
            - { name: DEFAULT_BLOCK_ADS, value: "true" }
            - { name: DEFAULT_STEALTH, value: "true" }

  persistence:
    datastore:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi

  service:
    main:
      ports:
        http:
          port: 5000

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "changedetection.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: changedetection-tls-certificate
          hosts:
            - *host
