######################
# Jellyfin           #
######################

jellyfin:
  global:
    nameOverride: jellyfin

  controllers:
    main:
      strategy: Recreate

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups:
            - 44  # video
            - 109  # render

      containers:
        main:
          image:
            repository: jellyfin/jellyfin
            tag: 10.8.12
          env:
            TZ: Europe/Berlin
          resources:
            requests:
              gpu.intel.com/i915: "1"
            limits:
              gpu.intel.com/i915: "1"
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /health
                  port: 8096
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 50Gi
      annotations:
        'k8up.io/backup': 'true'
    cache:
      enabled: true
      type: emptyDir
    mediarr:
      enabled: true
      existingClaim: mediarr
      advancedMounts:
        main:
          main:
            - path: /filme
              subPath: filme
            - path: /serien
              subPath: serien

  service:
    main:
      ports:
        http:
          port: 8096


  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "jellyfin.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *host


######################
# Jellyseerr         #
######################

jellyseerr:
  global:
    nameOverride: jellyseerr

  controllers:
    main:
      strategy: RollingUpdate

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch

      containers:
        main:
          image:
            repository: fallenbagel/jellyseerr
            tag: 1.7.0
          env:
            TZ: Europe/Berlin
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: 5055
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      globalMounts:
        - path: /app/config
      annotations:
        'k8up.io/backup': 'true'

  service:
    main:
      ports:
        http:
          port: 5055

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "jellyseerr.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: jellyseerr-tls-certificate
          hosts:
            - *host


######################
# Prowlarr           #
######################

prowlarr:
  global:
    nameOverride: prowlarr

  controllers:
    main:
      strategy: RollingUpdate

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
        annotations:
          setGateway: "true"

      initContainers:
        01-init-db:
          image:
            repository: ghcr.io/onedr0p/postgres-init
            tag: 14.9
            pullPolicy: IfNotPresent
          envFrom: &envFrom
            - secretRef:
                name: prowlarr-secret

      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/prowlarr
            tag: 1.10.5.4116
          env:
            TZ: Europe/Berlin
            PROWLARR__PORT: &port 9696
            PROWLARR__AUTHENTICATION_METHOD: External
            PROWLARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          envFrom: *envFrom
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 2
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi

  service:
    main:
      ports:
        http:
          port: *port

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "prowlarr.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: prowlarr-tls-certificate
          hosts:
            - *host


######################
# Radarr             #
######################

radarr:
  global:
    nameOverride: radarr

  controllers:
    main:
      strategy: RollingUpdate

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
        annotations:
          setGateway: "true"

      initContainers:
        01-init-db:
          image:
            repository: ghcr.io/onedr0p/postgres-init
            tag: 14.9
            pullPolicy: IfNotPresent
          envFrom: &envFrom
            - secretRef:
                name: radarr-secret

      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/radarr
            tag: 5.1.3.8246
          env:
            TZ: Europe/Berlin
            RADARR__PORT: &port 7878
            RADARR__AUTHENTICATION_METHOD: External
            RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          envFrom: *envFrom
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 2
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
    mediarr:
      enabled: true
      existingClaim: mediarr

  service:
    main:
      ports:
        http:
          port: *port

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "radarr.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: radarr-tls-certificate
          hosts:
            - *host


######################
# Sonarr             #
######################

sonarr:
  global:
    nameOverride: sonarr

  controllers:
    main:
      strategy: RollingUpdate

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
        annotations:
          setGateway: "true"

      initContainers:
        01-init-db:
          image:
            repository: ghcr.io/onedr0p/postgres-init
            tag: 14.9
            pullPolicy: IfNotPresent
          envFrom: &envFrom
            - secretRef:
                name: sonarr-secret

      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/sonarr-develop
            tag: 4.0.0.733 # TODO: switch to stable after v4 release
          env:
            SONARR__PORT: &port 8989
            SONARR__AUTHENTICATION_METHOD: External
            SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          envFrom: *envFrom
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 2
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
    mediarr:
      enabled: true
      existingClaim: mediarr

  service:
    main:
      ports:
        http:
          port: *port

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "sonarr.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: sonarr-tls-certificate
          hosts:
            - *host


######################
# Bazarr             #
######################

bazarr:
  global:
    nameOverride: bazarr

  controllers:
    main:
      strategy: RollingUpdate

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
        annotations:
          setGateway: "true"
          k8up.io/backupcommand: >
            sh -c 'APIKEY=$(grep -m 1 "apikey" /config/config/config.ini | cut -d "=" -f 2 | xargs);
            curl -s -X POST "http://localhost:6767/api/system/backups?apikey=$APIKEY"; sleep 5;
            FILENAME=$(curl -s "http://localhost:6767/api/system/backups?apikey=$APIKEY" | jq -r ".data[0].filename");
            curl -s "http://localhost:6767/system/backup/download/$FILENAME?apikey=$APIKEY"'
          k8up.io/file-extension: .zip

      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/bazarr
            tag: 1.3.1
          env:
            TZ: Europe/Berlin
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: 6767
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 2
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      annotations:
        'k8up.io/backup': 'false'
    mediarr:
      enabled: true
      existingClaim: mediarr
      advancedMounts:
        main:
          main:
            - path: /filme
              subPath: filme
            - path: /serien
              subPath: serien

  service:
    main:
      ports:
        http:
          port: 6767

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "bazarr.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: bazarr-tls-certificate
          hosts:
            - *host


######################
# Autobrr            #
######################

autobrr:
  global:
    nameOverride: autobrr

  controllers:
    main:
      strategy: RollingUpdate

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
        annotations:
          setGateway: "true"

      containers:
        main:
          image:
            repository: ghcr.io/autobrr/autobrr
            tag: v1.33.0
          env:
            TZ: Europe/Berlin
            AUTOBRR__HOST: 0.0.0.0
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api/healthz/liveness
                  port: 7474
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 2
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      annotations:
        'k8up.io/backup': 'true'

  service:
    main:
      ports:
        http:
          port: 7474

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "autobrr.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: autobrr-tls-certificate
          hosts:
            - *host


######################
# Transmission       #
######################

transmission:
  global:
    nameOverride: transmission

  controllers:
    main:
      strategy: RollingUpdate

      pod:
        hostname: transmission
        annotations:
          setGateway: "true"
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch

      initContainers:
        01-init-themes:
          name: theme-provider
          image:
            repository: registry.gitlab.com/antoncuranz/transmission-themes
            tag: latest
          command:
            - sh
          args:
            - -c
            - |
              echo "Copying themes..."
              cp -R /opt/transmission-ui/* /themes

      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/transmission
            tag: 4.0.4
          env:
            TZ: Europe/Berlin
            TRANSMISSION__BLOCKLIST_URL: "https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz"
            TRANSMISSION__DOWNLOAD_DIR: "/downloads/mediarr"
            TRANSMISSION__INCOMPLETE_DIR_ENABLED: false
            TRANSMISSION__RPC_PORT: &port 9091
            TRANSMISSION__PEER_PORT: 9453
            TRANSMISSION__MESSAGE_LEVEL: 3
            TRANSMISSION__SPEED_LIMIT_DOWN_ENABLED: true
            TRANSMISSION__SPEED_LIMIT_DOWN: 20000
            TRANSMISSION_WEB_HOME: "/opt/transmission-ui/transmissionic"

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      annotations:
        'k8up.io/backup': 'true'
    mediarr:
      enabled: true
      existingClaim: mediarr
      advancedMounts:
        main:
          main:
            - path: /downloads/mediarr
              subPath: downloads
    autobrr:
      enabled: true
      existingClaim: autobrr
      advancedMounts:
        main:
          main:
            - path: /downloads/autobrr
    themes:
      enabled: true
      type: emptyDir
      advancedMounts:
        main:
          01-init-themes:
            - path: /themes
          main:
            - path: /opt/transmission-ui

  service:
    main:
      ports:
        http:
          port: *port

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "transmission.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: transmission-tls-certificate
          hosts:
            - *host
