######################
# Jellyseerr         #
######################

jellyseerr:
  global:
    nameOverride: jellyseerr

  controllers:
    main:
      strategy: RollingUpdate

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch

      containers:
        main:
          image:
            repository: fallenbagel/jellyseerr
            tag: 1.7.0
          env:
            TZ: Europe/Berlin
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: 5055
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      globalMounts:
        - path: /app/config
      annotations:
        'k8up.io/backup': 'true'

  service:
    main:
      ports:
        http:
          port: 5055

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "test.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: test-tls-certificate
          hosts:
            - *host
