---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: fireflyiii-db
spec:
  database: fireflyiii
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: fireflyiii-user
spec:
  role: fireflyiii
  database: fireflyiii-db
  secretName: database
  privileges: OWNER
  secretTemplate:
    TEST: "user={{ `{{ .Role }}` }} password={{ `{{ .Password }}` }}"
