---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fireflyiii-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#  dataSourceRef:
#    kind: ReplicationDestination
#    apiGroup: volsync.backube
#    name: fireflyiii-dst
