---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name fireflyiii-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ `{{ .S3_ENDPOINT }}` }}/fireflyiii"
        RESTIC_PASSWORD: "{{ `{{ .RESTIC_PASSWORD }}` }}"
        AWS_ACCESS_KEY_ID: "{{ `{{ .ACCESS_KEY_ID }}` }}"
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .ACCESS_SECRET_KEY }}` }}"
  dataFrom:
    - extract:
        key: b2-volsync
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: fireflyiii
spec:
  sourcePVC: fireflyiii-data
  trigger:
    schedule: "0 5 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: fireflyiii-volsync
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 2000
      fsGroup: 2000
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: fireflyiii-dst
spec:
  trigger:
    manual: restore-once
  restic:
    repository: fireflyiii-volsync
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    capacity: 5Gi
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 2000
      fsGroup: 2000