authentik:
  envValueFrom:
    AUTHENTIK_SECRET_KEY:
      secretKeyRef:
        name: authentik-secrets
        key: SECRET_KEY
    AUTHENTIK_POSTGRESQL__HOST:
      secretKeyRef:
        name: database-authentik-user
        key: HOST
    AUTHENTIK_POSTGRESQL__NAME:
      secretKeyRef:
        name: database-authentik-user
        key: DATABASE_NAME
    AUTHENTIK_POSTGRESQL__USER:
      secretKeyRef:
        name: database-authentik-user
        key: LOGIN
    AUTHENTIK_POSTGRESQL__PASSWORD:
      secretKeyRef:
        name: database-authentik-user
        key: PASSWORD

  volumeMounts:
    - name: tls-certs
      mountPath: /certs

  volumes:
    - name: tls-certs
      secret:
        secretName: authentik-tls-certificate

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host "authentik.serverton.de"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: authentik-tls-certificate
        hosts:
          - *host

  redis:
    enabled: true
