pod-gateway:
  image:
    repository: ghcr.io/ant0ncuranz/pod-gateway
    tag: dev@sha256:99d25085749354dd124e5d93c75a1042c5f42056f1781ae4f63702f93ef654a7
  routed_namespaces:
    - vpn
  settings:
    VPN_INTERFACE: wg0
    VPN_BLOCK_OTHER_TRAFFIC: true
    VPN_TRAFFIC_PORT: 1637
    NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16"
    VPN_LOCAL_CIDRS: "10.42.0.0/16 10.43.0.0/16"
    IPTABLES_NFT: yes
  webhook:
    namespaceSelector:
      label: "routed-gateway2"
    image:
      repository: ghcr.io/angelnu/gateway-admision-controller
      tag: v3.9.0
  publicPorts:
    - IP: 11
      hostname: terminal
      ports:
        - port: 48291
          type: udp
        - port: 48291
          type: tcp
  addons:
    vpn:
      enabled: true
      type: gluetun
      gluetun:
        image:
          repository: docker.io/qmcgaw/gluetun
          tag: v3.36.0
      envFrom:
        - secretRef:
            name: wireguard-config
      securityContext:
        capabilities:
          add: [ "NET_ADMIN" ]
      networkPolicy:
        enabled: true
        egress:
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
            ports:
              - port: 1637
                protocol: UDP
          - to:
              - namespaceSelector: {}
      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - if [ $(wget -q -O- https://ipinfo.io/country) == 'NL' ]; then exit 0; else exit $?; fi
        initialDelaySeconds: 30
        periodSeconds: 60
        failureThreshold: 1