pod-gateway:
  image:
    repository: ghcr.io/angelnu/pod-gateway
    tag: v1.8.1
  routed_namespaces:
    - vpn
  addons:
    vpn:
      enabled: true
      type: gluetun
      image:
        repository: docker.io/qmcgaw/gluetun
        tag: v3.35.0

      envFrom:
        - secretRef:
            name: wireguard-config
      securityContext:
        capabilities:
          add: [ "NET_ADMIN" ]

      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - if [ $(wget -q -O- https://ipinfo.io/country) == 'NL' ]; then exit 0; else exit $?; fi
        initialDelaySeconds: 30
        periodSeconds: 60
        failureThreshold: 1

      networkPolicy:
        enabled: true
        egress:
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
            ports:
              # VPN traffic port - change if your provider uses a different port
              - port: 1637
                protocol: UDP
              # TODO: only allow traffic in vpn namespace itself?
          - to:
              # Allow traffic within K8S - change if your K8S cluster uses a different CIDR
              - ipBlock:
                  cidr: 10.0.0.0/8
  settings:
    VPN_INTERFACE: wg0
    VPN_BLOCK_OTHER_TRAFFIC: true
    VPN_TRAFFIC_PORT: 1637
    VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"
#    NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16"