keycloak:
  production: true
  proxy: edge
  cache:
    enabled: false # fixes errors on import/export: https://github.com/keycloak/keycloak/issues/14733
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: "ipv4.cloudton.de"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostname: "keycloak.cloudton.de"
    tls: true
  postgresql:
    enabled: false
  externalDatabase:
    existingSecret: database-keycloak-user
    existingSecretHostKey: HOST
    existingSecretUserKey: LOGIN
    existingSecretPasswordKey: PASSWORD
    existingSecretDatabaseKey: DATABASE_NAME
  podAnnotations:
    k8up.io/backupcommand: sh -c '/opt/bitnami/keycloak/bin/kc.sh export --file /opt/bitnami/keycloak/data/finance-realm.json --realm finance --users realm_file > /dev/null && cat /opt/bitnami/keycloak/data/finance-realm.json'
    k8up.io/file-extension: .json
  initContainers:
    - name: theme-provider
      image: registry.gitlab.com/antoncuranz/keycloak-theme:latest
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /keywind/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme
  extraVolumeMounts:
    - name: theme
      mountPath: /opt/bitnami/keycloak/themes/keywind
  extraVolumes:
    - name: theme
      emptyDir: {}
