k8up:
  envVars:
    - name: BACKUP_GLOBAL_OPERATOR_NAMESPACE
      value: backup

rclone:
  image:
    repository: rclone/rclone
    tag: "1.63.1"
  init: |
    rclone rcd \
      --rc-no-auth \
      --rc-addr=:5572 &
    
    wait -n
    exit $?
  service:
    main:
      ports:
        restic:
          enabled: true
          port: 50001
          protocol: TCP
