k8up:
  envVars:
    - name: BACKUP_GLOBAL_OPERATOR_NAMESPACE
      value: backup

rclone:
  image:
    repository: rclone/rclone
    tag: "1.63.1"
  init: |
    rclone rcd \
      --rc-no-auth \
      --rc-addr=:5572 &
    
    rclone serve restic koofr:k8up \
      --addr=:9001 &

    wait -n
    exit $?
  persistence:
    config:
      name: rclone-config
      type: secret
