app-template:
  controller:
    strategy: RollingUpdate
  image:
    repository: ghcr.io/oznu/homebridge
    tag: "2023-01-08"
  service:
    main:
      ports:
        http:
          port: &port 8581
        shelly:
          port: 8181
  hostNetwork: true
  persistence:
    homebridge:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      annotations:
        'k8up.io/backup': 'true'
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "homebridge.serverton.de"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homebridge-tls-certificate
          hosts:
            - *host
  configMaps:
    config:
      enabled: true
      nameOverride: startup-sh
      data:
        startup.sh: |-
          #!/bin/sh
          npm install --save homebridge-shelly@latest
          npm install --save homebridge-tuya-platform@latest
  probes:
    liveness:
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /login
          port: *port
        initialDelaySeconds: 30
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 750Mi
