immich:
  image:
    # renovate: datasource=github-releases depName=immich-app/immich
    tag: v1.56.2
  immich:
    persistence:
      library:
        existingClaim: immich-data
  postgresql:
    enabled: true
    global:
      storageClass: local-path
  redis:
    enabled: true
    global:
      storageClass: local-path
  typesense:
    enabled: true
    persistence:
      tsdata:
        enabled: true
        storageClass: local-path
  proxy:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.cloudton.de"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: &host "immich.cloudton.de"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: immich-tls-certificate
            hosts:
              - *host
