immich:
  image:
    # renovate: datasource=github-releases depName=immich-app/immich
    tag: "v1.78.1"
  env:
    DB_HOSTNAME:
      valueFrom:
        secretKeyRef:
          name: database-immich-user
          key: HOST
    DB_USERNAME:
      valueFrom:
        secretKeyRef:
          name: database-immich-user
          key: LOGIN
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: database-immich-user
          key: PASSWORD
    DB_DATABASE_NAME:
      valueFrom:
        secretKeyRef:
          name: database-immich-user
          key: DATABASE_NAME
  immich:
    persistence:
      library:
        existingClaim: immich-data
  redis:
    enabled: true
    master:
      persistence:
        storageClass: truenas-iscsi
        annotations:
          k8up.io/backup: 'false'
  typesense:
    enabled: true
    persistence:
      tsdata:
        enabled: true
        storageClass: truenas-iscsi
        annotations:
          k8up.io/backup: 'false'
  proxy:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.cloudton.de"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: &host "immich.cloudton.de"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: immich-tls-certificate
            hosts:
              - *host
