apiVersion: v2
name: finance
version: 0.0.0
dependencies:
  - name: app-template
    alias: finance-backend
    version: 1.5.1
    repository: https://bjw-s.github.io/helm-charts
  - name: app-template
    alias: finance-frontend
    version: 1.5.1
    repository: https://bjw-s.github.io/helm-charts
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.9.0
