finance-backend:
  global:
    nameOverride: backend
  controller:
    strategy: RollingUpdate
  image:
    repository: registry.gitlab.com/antoncuranz/financeq
    tag: dev
  imagePullSecrets:
    - name: gitlab-token
  env:
    KEYCLOAK_REALM_URL: "https://keycloak.serverton.de/realms/finance"
    KEYCLOAK_CLIENT_ID: "finance-backend"
    CORS_ALLOW_ORIGINS: "https://finance.serverton.de"
    CRON_ALERT_DELIVERY: "0 */15 * * * ?"
    CRON_TRANSACTION_VALIDATION: "0 0 */1 * * ?"
    POSTGRES_URL:
      valueFrom:
        secretKeyRef:
          name: database-finance-user
          key: POSTGRES_JDBC_URL
    POSTGRES_USER:
      valueFrom:
        secretKeyRef:
          name: database-finance-user
          key: LOGIN
    POSTGRES_PASSWD:
      valueFrom:
        secretKeyRef:
          name: database-finance-user
          key: PASSWORD
  envFrom:
    - secretRef:
        name: finance-secrets
  service:
    main:
      ports:
        http:
          port: &port 8080
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "financeq.serverton.de"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: financeq-tls-certificate
          hosts:
            - *host

finance-frontend:
  global:
    nameOverride: frontend
  controller:
    strategy: RollingUpdate
  image:
    repository: registry.gitlab.com/antoncuranz/financeionic
    tag: dev
  imagePullSecrets:
    - name: gitlab-token
  env:
    KEYCLOAK_URL: "https://keycloak.serverton.de"
    KEYCLOAK_REALM: "finance"
    KEYCLOAK_CLIENT_ID: "finance-frontend"
    BACKEND_URL: "https://financeq.serverton.de"
  service:
    main:
      ports:
        http:
          port: &port 80
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "finance.serverton.de"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: finance-tls-certificate
          hosts:
            - *host
