app-template:
  controller:
    strategy: RollingUpdate
  image:
    repository: haugene/transmission-openvpn
    tag: 5.0.2
  env:
    TZ: Europe/Berlin
    LOCAL_NETWORK: 10.42.0.0/16
    OPENVPN_PROVIDER: custom
    OPENVPN_USERNAME: user
    OPENVPN_PASSWORD: pass
    TRANSMISSION_WEB_UI: combustion
  persistence:
    data:
      enabled: true
      type: hostPath
      hostPath: /srv/Transmission
      mountPath: /data
    openvpn-config:
      enabled: true
      type: secret
      name: openvpn-config
    custom:
      enabled: true
      type: emptyDir
      mountPath: /etc/openvpn/custom
  initContainers:
    config-provider:
      name: config-provider
      image: busybox:1.36
      command: ['/bin/sh', '-c', 'cp /openvpn-config/* /custom']
      volumeMounts:
        - name: openvpn-config
          mountPath: /openvpn-config
        - name: custom
          mountPath: /custom
  service:
    main:
      ports:
        http:
          port: &port 9091
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.cloudton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "transmission.cloudton.de"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: transmission-tls-certificate
          hosts:
            - *host
  securityContext:
    allowPrivilegeEscalation: true
    capabilities:
      add:
        - NET_ADMIN
    privileged: true
  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        exec:
          command: ["ping", "-I", "tun0", "-c", "1", "google.com"]
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
    readiness: *probes
    startup:
      enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 1024Mi
    limits:
      memory: 4096Mi
