app-template:
  controller:
    strategy: RollingUpdate
  image:
    repository: actualbudget/actual-server
    tag: 23.12.1
  env:
    - name: TZ
      value: "Europe/Berlin"
    - name: ACTUAL_NORDIGEN_SECRET_ID
      valueFrom:
        secretKeyRef:
          name: actual-secrets
          key: NORDIGEN_SECRET_ID
    - name: ACTUAL_NORDIGEN_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: actual-secrets
          key: NORDIGEN_SECRET_KEY
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi
  service:
    main:
      ports:
        http:
          port: &port 5006
  # probes:
  #   liveness: &probes
  #     enabled: true
  #     custom: true
  #     spec:
  #       httpGet:
  #         path: /health
  #         port: *port
  #       initialDelaySeconds: 0
  #       periodSeconds: 10
  #       timeoutSeconds: 1
  #       failureThreshold: 3
  #   readiness: *probes
  #   startup:
  #     enabled: false
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "actual.serverton.de"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: actual-tls-certificate
          hosts:
            - *host
