---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: prowlarr-db
spec:
  database: prowlarr
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: prowlarr-user
spec:
  role: prowlarr
  database: prowlarr-db
  secretName: database
  privileges: OWNER
