---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediarr-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/SSD/k8s/mediarr"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediarr
  annotations:
    'k8up.io/backup': 'false'
spec:
  volumeName: mediarr-pv
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
