---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-autobrr
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: nfs-autobrr
    volumeAttributes:
      server: 192.168.1.2
      share: /mnt/SSD/k8s/nfs/autobrr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autobrr
  annotations:
    'k8up.io/backup': 'false'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: nfs-autobrr
  storageClassName: nfs
