---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mediarr
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-mediarr
  mountOptions:
    - nfsvers=4
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: nfs-mediarr
    volumeAttributes:
      server: 192.168.1.2
      share: /mnt/SSD/k8s/nfs/mediarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediarr
  annotations:
    'k8up.io/backup': 'false'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: nfs-mediarr
  storageClassName: nfs-mediarr
