---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: sonarr-db
spec:
  database: sonarr
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: sonarr-user
spec:
  role: sonarr
  database: sonarr-db
  secretName: database
  privileges: OWNER
