---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.1.2"
  share: "/mnt/SSD/k8s/nfs"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - noatime
  - nfsvers=4
