democratic-csi:
  driver:
    config:
      driver: freenas-api-nfs
      httpConnection:
        protocol: http
        apiKey: 1-M4DHWLIBfTGasos8jXmSflDWuxGn1jHPGUc8SVrcqeNpx4FB23XcrIXyVuB3SZFM
        host: 192.168.0.103
        port: 80
        allowInsecure: true
      zfs:
        datasetParentName: nvme2/k8s/nfs/vols
        detachedSnapshotsDatasetParentName: nvme2/k8s/nfs/snaps
        datasetEnableQuotas: true
        datasetEnableReservation: false
        datasetPermissionsMode: "0777"
        datasetPermissionsUser: 0
        datasetPermissionsGroup: 0
      nfs:
        shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
        shareHost: 192.168.0.103
        shareAlldirs: false
        shareAllowedHosts: []
        shareAllowedNetworks: []
        shareMaprootUser: root
        shareMaprootGroup: root
        shareMapallUser: ""
        shareMapallGroup: ""
  
  csiDriver:
    # should be globally unique for a given cluster
    name: "org.democratic-csi.nfs-api"
  
  storageClasses:
    - name: truenas
      defaultClass: true
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
        - noatime
        - nfsvers=4
  
  volumeSnapshotClasses:
    - name: truenas2
      annotations: {}
      labels: {}
      deletionPolicy: Retain
      parameters:
