democratic-csi:
  driver:
    config:
      driver: zfs-local-dataset

      zfs:
        datasetParentName: zroot/mediarr/v
        detachedSnapshotsDatasetParentName: zroot/mediarr/s

        datasetEnableQuotas: true
        datasetEnableReservation: false

        # can be used to override defaults if necessary
        # the example below is useful for TrueNAS 12
        cli:
        #  sudoEnabled: true
        #  leave paths unset for auto-detection
          paths:
            zfs: /run/current-system/sw/bin/zfs
            zpool: /run/current-system/sw/bin/zpool
            sudo: /run/current-system/sw/bin/sudo
            chroot: /run/current-system/sw/bin/chroot

  csiDriver:
    # should be globally unique for a given cluster
    name: "org.democratic-csi.zfs-local-dataset"
    attachRequired: false
    storageCapacity: true
    fsGroupPolicy: File

  controller:
    enabled: true
    strategy: node
    externalProvisioner:
      extraArgs:
        - --leader-election=false
        - --node-deployment=true
        - --node-deployment-immediate-binding=false
        - --feature-gates=Topology=true
        - --strict-topology=true
        - --enable-capacity=true
        - --capacity-ownerref-level=1

    externalAttacher:
      enabled: false

    # distributed support is not yet ready
    externalResizer:
      enabled: false

    externalSnapshotter:
      enabled: true
      extraArgs:
        - --leader-election=false
        - --node-deployment=true

  storageClasses:
    - name: zfs
      defaultClass: true
      reclaimPolicy: Retain
      volumeBindingMode: WaitForFirstConsumer
      # distributed support is not yet ready for expansion
      allowVolumeExpansion: false
      parameters:
        fsType: zfs

  volumeSnapshotClasses:
    - name: zfs
      annotations:
        snapshot.storage.kubernetes.io/is-default-class: "true"
      deletionPolicy: Retain
      parameters:
        detachedSnapshots: false
