apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup-test-3
  namespace: prowlarr
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    rest:
      url: "http://restic-restic-rest-server.restic.svc.cluster.local:8000"
