apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule-test
  namespace: prowlarr
spec:
  backend:
    rest:
      url: "http://restic-restic-rest-server.restic.svc.cluster.local:8000"
  backup:
    schedule: '*/5 * * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    # optional
    #promURL: https://prometheus-io-instance:8443
  check:
    schedule: '0 1 * * 1'
    # optional
    #promURL: https://prometheus-io-instance:8443
  prune:
    schedule: '0 1 * * 0'
    retention:
      keepLast: 5
      keepDaily: 14
