---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: immich-db
spec:
  database: postgres
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: immich-user
spec:
  role: immich
  database: test-db
  secretName: testsecret
  privileges: OWNER