---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  #dataSourceRef:
  #  kind: ReplicationDestination
  #  apiGroup: volsync.backube
  #  name: immich-dst
