apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data-pv
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: immich-data
  hostPath:
    path: /mnt/HDD1/Immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: immich-data
spec:
  storageClassName: manual
  volumeName: immich-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
