---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-immich
  mountOptions:
    - nfsvers=4
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: nfs-immich
    volumeAttributes:
      server: 192.168.1.2
      share: /mnt/SSD/k8s/nfs/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: immich
  name: immich-data
  annotations:
    k8up.io/backup: 'true'
spec:
  volumeName: nfs-immich
  storageClassName: nfs-immich
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
