apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: immich
  name: immich-data
  annotations:
    k8up.io/backup: 'true'
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
