apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: immich
  name: immich-data
spec:
  storageClassName: truenas-nfs
  volumeName: immich-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
