pihole:
  serviceDns:
    type: LoadBalancer
    externalTrafficPolicy: "Cluster"
    annotations:
      metallb.universe.tf/allow-shared-ip: default
  serviceDhcp:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
    hosts:
      - "pihole.serverton.de"
    tls:
      - secretName: pihole-tls-certificate
        hosts:
          - "pihole.serverton.de"
  persistentVolumeClaim:
    enabled: true
    storageClass: truenas-iscsi
    annotations:
      'k8up.io/backup': 'true'
  podAnnotations:
    k8up.io/backupcommand: sh -c 'pihole -a -t k8up.tar.gz && cat k8up.tar.gz'
    k8up.io/file-extension: .tar.gz
  DNS1: 1.1.1.1
  DNS2: 1.0.0.1
  ftl:
    BLOCK_ICLOUD_PR: false
