transmission:
  global:
    nameOverride: transmission
  hostname: terminal
  controller:
    strategy: RollingUpdate
  image:
    repository: ghcr.io/linuxserver/transmission
    tag: version-4.0.4-r0
  env:
    TZ: Europe/Berlin
  service:
    main:
      ports:
        http:
          port: 9091
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "test.serverton.de"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: test-tls-certificate
          hosts:
            - *host
