######################
# Transmission       #
######################

transmission:
  global:
    nameOverride: transmission
  hostname: transmission
  controller:
    strategy: RollingUpdate
  image:
    repository: ghcr.io/onedr0p/transmission
    tag: 4.0.4
  env:
    TRANSMISSION__IDLE_SEEDING_LIMIT_ENABLED: true
    TRANSMISSION__IDLE_SEEDING_LIMIT: 14400
    TRANSMISSION__PEER_PORT: 9453
    TRANSMISSION_WEB_HOME: "/opt/transmission-ui/combustion-release"
  podAnnotations:
    setGateway: "false"
  initContainers:
    theme-provider:
      name: theme-provider
      image: registry.gitlab.com/antoncuranz/transmission-themes:latest
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying themes..."
          cp -R /opt/transmission-ui/* /themes
      volumeMounts:
        - name: themes
          mountPath: /themes
  persistence:
    themes:
      enabled: true
      type: emptyDir
      mountPath: /opt/transmission-ui
      annotations:
        'k8up.io/backup': 'false'
#    config:
#      enabled: true
#      accessMode: ReadWriteOnce
#      size: 250Mi
#      annotations:
#        'k8up.io/backup': 'true'
    downloads:
      enabled: true
      storageClass: truenas-nfs
      accessMode: ReadWriteMany
      size: 10Gi
      mountPath: /downloads
      annotations:
        'k8up.io/backup': 'false'
  service:
    main:
      ports:
        http:
          port: 9091
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "test.serverton.de"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: test-tls-certificate
          hosts:
            - *host
#  podSecurityContext:
#    runAsUser: 568
#    runAsGroup: 568
#    fsGroup: 568
#    fsGroupChangePolicy: OnRootMismatch
