apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-data
  annotations:
    k8up.io/backup: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
