app-template:
  defaultPodOptions:
    hostNetwork: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: alexbabel/owntone
            tag: latest

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi

  service:
    main:
      ports:
        http:
          port: 3689

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "owntone.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: sabnzbd-tls-certificate
          hosts:
            - *host
