apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: shelly-monitor
spec:
  endpoints:
    - interval: 15s
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: "shelly-exporter"