apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    per_listener_settings false
    listener 8883
    cafile /etc/ssl/certs/ca-certificates.crt
    keyfile /mosquitto/certs/tls.key
    certfile /mosquitto/certs/tls.crt
    allow_anonymous false
    persistence true
    persistence_location /mosquitto/data/
    connection_messages false
    password_file /mosquitto/mosquitto_pwd

    connection bridge-to-tibber
    bridge_cafile /share/mosquitto/tibber_cert/CA.ca
    bridge_certfile /share/mosquitto/tibber_cert/Cert.crt
    bridge_keyfile /share/mosquitto/tibber_cert/Priv.key
    address a1zhmn1192zl1a.iot.eu-west-1.amazonaws.com:8883
    clientid 4022d8f438cc0
    try_private false
    notifications false
    topic $aws/# out
    topic tibber-bridge/bd693e43a70d4b19b8f7a6d372d210ff/receive in