apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    per_listener_settings false
    listener 1883
    allow_anonymous false
    persistence true
    persistence_location /mosquitto/data/
    connection_messages false
    password_file /mosquitto/mosquitto_pwd