---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: finance-db
spec:
  database: finance
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: finance-user
spec:
  role: finance
  database: finance-db
  secretName: database
  privileges: OWNER