shelly-exporter:
  global:
    nameOverride: shelly-exporter

  controllers:
    main:
      containers:
        main:
          image:
            repository: php
            tag: 8-apache
          env:
            SHELLY_HOSTNAME: 192.168.4.31
            SHELLY_HTTP_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: shelly-exporter
                  key: HTTP_PASSWORD

  persistence:
    script:
      enabled: true
      type: secret
      name: shelly-exporter
      globalMounts:
        - path: /var/www/html

  service:
    main:
      ports:
        http:
          port: 80

mosquitto:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/library/eclipse-mosquitto
            tag: 2.0.1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ "ALL" ] }
          resources:
            requests:
              cpu: 10m
            limits:
              memory: 16Mi
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
  service:
    main:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: default
      ports:
        http:
          port: 1883
  persistence:
    config:
      enabled: true
      globalMounts:
        - path: /mosquitto/config
    data:
      enabled: true
      globalMounts:
        - path: /mosquitto/data
    logs:
      type: emptyDir
      globalMounts:
        - path: /mosquitto/log

node-red:
  controllers:
    main:
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: "OnRootMismatch"

      containers:
        main:
          image:
            repository: docker.io/nodered/node-red
            tag: 3.1.3
          envFrom:
            - secretRef:
                name: node-red-secret
          resources:
            requests:
              cpu: 5m
              memory: 512Mi
            limits:
              memory: 512Mi
  service:
    main:
      ports:
        http:
          port: 1880
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "node-red.serverton.de"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: node-red-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      globalMounts:
        - path: /data