signal-cli:
  global:
    nameOverride: signal-cli
  controller:
    strategy: RollingUpdate
  image:
    repository: bbernhard/signal-cli-rest-api
    tag: 0.83
  env:
    TZ: "Europe/Berlin"
    AUTO_RECEIVE_SCHEDULE: "0 22 * * *"
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      mountPath: /home/.local/share/signal-cli
      annotations:
        'k8up.io/backup': 'true'
  service:
    main:
      ports:
        http:
          port: &port 8080
  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /v1/health
          port: *port
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
    readiness: *probes
    startup:
      enabled: false