---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name unifi-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ `{{ .S3_ENDPOINT }}` }}/unifi"
        RESTIC_PASSWORD: "{{ `{{ .RESTIC_PASSWORD }}` }}"
        AWS_ACCESS_KEY_ID: "{{ `{{ .ACCESS_KEY_ID }}` }}"
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .ACCESS_SECRET_KEY }}` }}"
  dataFrom:
    - extract:
        key: b2-volsync
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: unifi
spec:
  sourcePVC: unifi-config
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: unifi-volsync-secret
    moverSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
    retain:
      hourly: 24
      daily: 7
      weekly: 5
#---
#apiVersion: volsync.backube/v1alpha1
#kind: ReplicationDestination
#metadata:
#  name: unifi-dst
#spec:
#  trigger:
#    manual: restore-once
#  restic:
#    repository: unifi-volsync-secret
#    copyMethod: Snapshot # must be Snapshot
#    accessModes: ["ReadWriteOnce"]
#    capacity: "1Gi"
#    moverSecurityContext:
#      runAsUser: 999
#      runAsGroup: 999
#      fsGroup: 999