firefly-iii:
  image:
    repository: fireflyiii/core
    tag: "version-6.1.18"

  persistence:
    enabled: true
    existingClaim: "fireflyiii-data"

  config:
    existingSecret: "database-fireflyiii-user"

    env:
      DB_CONNECTION: pgsql
      DB_PORT: "5432"
      DEFAULT_LANGUAGE: "en_US"
      DEFAULT_LOCALE: "equal"
      TZ: "Europe/Berlin"
      TRUSTED_PROXIES: "**"

  podSecurityContext:
     fsGroup: 2000

#  securityContext:
#     capabilities:
#       drop:
#       - ALL
#     runAsNonRoot: true
#     runAsUser: 1000

  ingress:
    enabled: true
    className: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host "firefly.serverton.de"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: fireflyiii-tls-certificate
        hosts:
          - *host

importer:
  image:
    repository: fireflyiii/data-importer
    tag: "version-1.5.2"

  fireflyiii:
    url: "http://fireflyiii-firefly-iii.fireflyiii.svc.cluster.local:80"
