democratic-csi:
  driver:
    existingConfigSecret: democratic-csi-iscsi-secret
    config:
      driver: freenas-api-iscsi
  
  csiDriver:
    # should be globally unique for a given cluster
    name: "org.democratic-csi.iscsi"
  
  storageClasses:
    - name: truenas-iscsi
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: xfs
      mountOptions: []