minecraft:
  minecraftServer:
    eula: "TRUE"
    type: "PAPER"
    serviceType: LoadBalancer
    memory: 6G
    rcon:
      enabled: true
      withGeneratedPassword: true
  extraEnv:
    TZ: "Europe/Berlin"
    ENABLE_AUTOPAUSE: true
    AUTOPAUSE_TIMEOUT_EST: 10
    AUTOPAUSE_TIMEOUT_INIT: 10
    AUTOPAUSE_TIMEOUT_KN: 10
  serviceAnnotations:
    metallb.universe.tf/allow-shared-ip: default
