minecraft:
  minecraftServer:
    eula: "TRUE"
    type: "PAPER"
    serviceType: LoadBalancer
    memory: 6G
    maxTickTime: -1 # autopause
    rcon:
      enabled: true
      withGeneratedPassword: true
  extraEnv:
    TZ: "Europe/Berlin"
    ENABLE_AUTOPAUSE: true
    AUTOPAUSE_TIMEOUT_EST: 10
    AUTOPAUSE_TIMEOUT_INIT: 10
    AUTOPAUSE_TIMEOUT_KN: 10
    JVM_DD_OPTS: "disable.watchdog:true" # autopause
  persistence:
    storageClass: "local-path"
    dataDir:
      enabled: true
  serviceAnnotations:
    metallb.universe.tf/allow-shared-ip: default

  # autopause hacks
  securityContext:
    allowPrivilegeEscalation: true
    capabilities:
      add: [ "NET_RAW" ]
  initContainers:
    - name: patch-autopause
      image: itzg/minecraft-server:latest
      command:
        - sh
      args:
        - -c
        - |
          cp /auto/autopause-daemon.sh /patch
          sed -i 's/sudo //g' /patch/autopause-daemon.sh
      volumeMounts:
        - name: patch
          mountPath: /patch
  extraVolumes:
    - volumeMounts:
        - name: patch
          mountPath: /auto/autopause-daemon.sh
          subPath: autopause-daemon.sh
      volumes:
        - name: patch
          emptyDir: {}
