minecraft:
#  image:
#    repository: "ghcr.io/jjgadgets/minecraft-server"
#    tag: "java17-graalvm"
  minecraftServer:
    eula: "TRUE"
    type: "PAPER"
    serviceType: LoadBalancer
    memory: 6G
    maxTickTime: -1 # autopause
    rcon:
      enabled: true
      withGeneratedPassword: true
  extraEnv:
    TZ: "Europe/Berlin"
    ENABLE_AUTOPAUSE: true
    AUTOPAUSE_TIMEOUT_EST: 10
    AUTOPAUSE_TIMEOUT_INIT: 10
    AUTOPAUSE_TIMEOUT_KN: 10
    AUTOPAUSE_SUDO: false
    JVM_DD_OPTS: "disable.watchdog:true"
  securityContext:
    allowPrivilegeEscalation: true
    capabilities:
      add: [ "NET_RAW" ]
#  podSecurityContext:
#    runAsNonRoot: false
  serviceAnnotations:
    metallb.universe.tf/allow-shared-ip: default
