ingress-nginx:
  controller:
    service:
      enableHttp: false
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    tcp:
      2003: "monitoring-system/monitoring-system-influxdb:2003"
