ingress-nginx:
  controller:
    service:
      enableHttp: false
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    extraArgs:
      tcp-services-configmap: "ingress-nginx/tcp-services"
      udp-services-configmap: "ingress-nginx/udp-services"
